#!/usr/bin/env bash

if mountpoint -q /boot/efi; then
	grub2-install --target=$(uname -m)-efi --bootloader-id=grub \
     --removable --recheck --efi-dir=/boot/efi
	# undo Red Hat's sixteenbit patch since it breaks UEFI booting
	sed -i -e 's/sixteenbit="16"/sixteenbit=""/' /etc/grub.d/10_linux
	grub2-mkconfig -o /boot/grub2/grub.cfg
	# in case 10_linux has been somehow over-written with a bad copy
	# patch the grub.cfg configuration directly to ensure it's correct
	sed -i 's/linux16/linuxefi/' /boot/grub2/grub.cfg
	sed -i 's/initrd16/initrdefi/' /boot/grub2/grub.cfg
	sed -i 's/\sro\s/ rw /' /boot/grub2/grub.cfg
else
	echo "ESP is not mounted to /boot/efi"
	return 1
fi

# mount tmpfs manually instead of getting systemd to do it
#if [ $(grep -c "tmpfs" /etc/fstab) -eq 0 ]; then
#	echo "tmpfs	/tmp	tmpfs	rw,nodev,nosuid		0	0" >> /etc/fstab
#fi
