#!/usr/bin/env bash

ROOT=$(mount | grep " / "|sed -rn "s:^(/(\w+/)+[a-z]+)([0-9]+) .*$:\1@\3:p")
ROOT_DEV=$(echo $ROOT|cut -d @ -f1)
ROOT_PART=$(echo $ROOT|cut -d @ -f2)

growpart "$ROOT_DEV" "$ROOT_PART"
resize2fs "$ROOT_DEV$ROOT_PART"

systemctl disable scw-grow-root
